### ISSUE TITLE
[퍼블리싱 QA] 프로필 페이지 퍼블리싱 이슈

### ISSUE THREAD

**Issue by minsoo-web** [WebVolume/volume-client#15]
1. 프로필 사진 업로드 버튼 반응형에서 줄바꿈 처리 되는 이슈
2. 프로필 배경 사진 업로드 버튼 반응형에서 줄바꿈 처리 되는 이슈
3. Like, Track 리스트 아이템의 SVG 아이콘들 크기가 32px로 고정인 이슈
  3-1. 🚀 아이콘 버튼의 경우 title 달아주기
4. Like, Track 리스트 아이템 반응형에서 레이아웃 깨지는 현상
5. PlayList 에서 앨범 아트? 정사각형이 아닌 이슈 (데스크톱)
6. `관련있는 트랙` 요소 반응형 처리 미흡 이슈
  6-1. 좋아요, 재생 횟수 의 p태그 요소
  6-2 더보기 줄바꿈 현상

**Comment by Yeom-JinHo** [comment]
1,2번 --> 디자인시안 지키면 줄바꿈처리만 막는게 최선인데 저렇게 삐져나온것도 추가적으로 처리해야할까요?

<img width="1213" alt="스크린샷 2022-02-27 오후 3 49 39" src="https://user-images.githubusercontent.com/81306489/155871662-2ea2ff2b-67ab-45de-876d-3f52434ff8fb.png">

3번 --> 수정완료. 추가적으로 date부분도 확인하여 수정.

<img width="906" alt="스크린샷 2022-02-27 오후 4 13 51" src="https://user-images.githubusercontent.com/81306489/155872503-7e7b8295-7cbb-4e06-afff-901fb5c8cc90.png">

3-1 --> 아이콘 변경후 툴팁까지 달아주었습니다. 현재 제 브라우저에서 툴팁이 안나오는 이슈가 있습니다 ㅠㅠ 한번 툴팁 확인부탁드릴게요!!

<img width="852" alt="스크린샷 2022-02-27 오후 4 39 36" src="https://user-images.githubusercontent.com/81306489/155873232-add44b47-ec3b-4ea7-8286-f92bee5a6bae.png">

4-- > 수정완료. (정사각형 앨범 뷰도 작업)
<img width="825" alt="스크린샷 2022-02-27 오후 7 17 37" src="https://user-images.githubusercontent.com/81306489/155878421-449bc4c5-a7e1-4a78-894b-8678c54ea10b.png">


5. --> 디자인이 모두 정사각형 뷰가 아니여서 작업했으나. 이 부분 희윤님께 여쭤보고 다시 정사각형으로 작업하였습니다.
<img width="810" alt="스크린샷 2022-02-27 오후 7 21 49" src="https://user-images.githubusercontent.com/81306489/155878527-c0b7c0c7-2d1c-4ed7-b4ca-aabb58b33810.png">

6. --> 수정완료  
<img width="593" alt="스크린샷 2022-02-27 오후 7 48 59" src="https://user-images.githubusercontent.com/81306489/155879349-008fdecf-0376-4b6d-b2dd-6702513aa902.png">

<img width="312" alt="스크린샷 2022-02-27 오후 7 49 13" src="https://user-images.githubusercontent.com/81306489/155879348-e87f78a3-a45a-4e19-ae31-93e729339cbc.png">

**Comment by minsoo-web** [comment]
1번 사항만 처리 완료되면 다시 코멘트 남겨주세요~!

**Comment by Yeom-JinHo** [comment]
넵 처리했습니다!

**Comment by minsoo-web** [comment]
확인되어 이슈 닫겠습니다~
