### ISSUE TITLE
[퍼블리싱 QA] 프로필 페이지 이슈

### ISSUE THREAD

**Issue by minsoo-web** [WebVolume/volume-client#17]
1. 프로필 페이지 전반적으로 elipsis 처리 (text-overflow 글자 끝에 ... 처리하는 거)
2. PlayList의 아이콘 버튼들 title 처리
3. 업로드 프로필 사진 버튼 opacity -> rgba 처리

**Comment by Yeom-JinHo** [comment]
1. 수정완료.
<img width="738" alt="스크린샷 2022-02-28 오전 11 29 44" src="https://user-images.githubusercontent.com/81306489/155920181-7aa48bd3-4ed3-4a33-9ba8-120c3ddffa15.png">


2. 수정완료.
<img width="817" alt="스크린샷 2022-02-28 오후 12 36 16" src="https://user-images.githubusercontent.com/81306489/155920185-3caebf28-5b76-4197-8dd1-ae85123f1431.png">

3. 아직 해결하지 못하여 저녁에 다시 한번 확인하고 코멘트 남기겠습니다!

**Comment by minsoo-web** [comment]
넵 감사합니다~! 확인 완료되시면 개인 연락 한 번 주세요!

**Comment by Yeom-JinHo** [comment]
3. rgba는 처리하였고 backdrop-filter 처리까지 하였는데 민수님처럼 처리가 안되네요... 주말에 시간날때 다시 한번 확인해보겠습니다ㅠㅠ 원인을 못찾겠네요

**Comment by Yeom-JinHo** [comment]
<img width="1367" alt="스크린샷 2022-03-09 오후 10 57 00" src="https://user-images.githubusercontent.com/81306489/157455918-a01bdcb4-6de7-4c78-b3f6-198a2b67a12b.png">

3번 해결하지 못해서.. 디자이너분과 상의해서 색상변경하였습니다--! 변경한 내용 푸쉬했습니다 :)

**Comment by minsoo-web** [comment]
확인 완료했습니다~!
