### ISSUE TITLE
[버그] 상단바 퍼블리싱 수정

### ISSUE THREAD

**Issue by Yeom-JinHo** [WebVolume/volume-client#6]
<img width="1674" alt="스크린샷 2022-02-03 오후 8 49 02" src="https://user-images.githubusercontent.com/81306489/152337285-811f4186-7013-4978-9348-c47e9db43eec.png">

TopNav 부분 왼쪽검은색 부분 혹시 의도하신건가요? 확인부탁드립니다!
그리고 margin말고 padding으로 하신 이유 있는건가요?

카톡으로 여쭤봐도 되는데 사실 저희 디자인상 고치지 않아도 되는 부분이고, 이슈탭 한번 사용해보고 싶어서 써봤습니다 :)

**Comment by minsoo-web** [comment]
제가 메인 레이아웃 그리드 시스템을 잘못 이해해서 잘못 만든 거구 
가로로 100% 검정색 처리 하는 게 맞습니다 ㅠ 이 부분 제가 수정해서 dev로 업로드 할게요

**Comment by minsoo-web** [comment]
수정된 이슈로 close하겠습니다~!
