### ISSUE TITLE
<a>태그 font color 이슈

### ISSUE THREAD

**Issue by Yeom-JinHo** [WebVolume/volume-client#8]
<img width="661" alt="스크린샷 2022-02-12 오후 6 59 16" src="https://user-images.githubusercontent.com/81306489/153706636-5b5e7349-0666-40d3-bd19-dafa770522f4.png">
<img width="578" alt="스크린샷 2022-02-12 오후 6 58 44" src="https://user-images.githubusercontent.com/81306489/153706638-3334e088-7be8-44bb-bf7e-87fe4338e1e1.png">

위 사진과 같이 a 태그만 폰트 컬러를 상속받지 못하고 보라색으로 표기되는데
이거 혹시 a 태그 일일히 바꾸기보다 reset에서 관리해주려고 했는데 그러면 전체 a태그 색깔이 바뀔꺼 같아서..
혹시 -webkit-link 없애고 font Color 상속 받는 방법아실까요 ㅠ

**Comment by minsoo-web** [comment]
<img width="201" alt="스크린샷 2022-02-12 오후 7 24 21" src="https://user-images.githubusercontent.com/57122180/153707444-61154cd7-93dd-4689-86ce-50e5cddcafcc.png">
reset.css에서 이렇게 하시면 될겁니다!

**Comment by Yeom-JinHo** [comment]
감사합니다:)
